# Generated by Django 3.2.16 on 2022-12-14 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure', models.TextField(blank=True, help_text='Введите причину отказа', null=True, verbose_name='Причина отказа')),
                ('review', models.CharField(choices=[('Ожидание', 'Ожидание'), ('Отказано', 'Отказано'), ('Одобрено', 'Одобрено')], default='Ожидание', max_length=8, verbose_name='Одобрение')),
                ('fio_user', models.CharField(max_length=150, verbose_name='Ваше ФИО')),
                ('fio_mother', models.CharField(max_length=150, verbose_name='ФИО Матери')),
                ('fio_father', models.CharField(max_length=150, verbose_name='ФИО Отца')),
                ('date_of_birth', models.DateTimeField(verbose_name='Дата рождения')),
                ('serial', models.CharField(max_length=25, verbose_name='Серия паспорта')),
                ('number', models.CharField(max_length=25, verbose_name='Номер паспорта')),
                ('phone', models.CharField(max_length=20, null=True, unique=True, verbose_name='Номер телефона для связи')),
                ('image', models.ImageField(help_text='Загрузите фото', upload_to='services/', verbose_name='Фото на паспорт')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Замена паспорта',
                'verbose_name_plural': 'Замена паспортов',
                'ordering': ['-pub_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Extradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure', models.TextField(blank=True, help_text='Введите причину отказа', null=True, verbose_name='Причина отказа')),
                ('review', models.CharField(choices=[('Ожидание', 'Ожидание'), ('Отказано', 'Отказано'), ('Одобрено', 'Одобрено')], default='Ожидание', max_length=8, verbose_name='Одобрение')),
                ('fio_user', models.CharField(max_length=150, verbose_name='Ваше ФИО')),
                ('fio_mother', models.CharField(max_length=150, verbose_name='ФИО Матери')),
                ('fio_father', models.CharField(max_length=150, verbose_name='ФИО Отца')),
                ('phone', models.CharField(max_length=20, null=True, unique=True, verbose_name='Номер телефона для связи')),
                ('birth_certificate', models.CharField(max_length=25, verbose_name='Номер свидетельства о рождении')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(help_text='Загрузите фото', null=True, upload_to='services/', verbose_name='Фото на паспорт')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraditions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Выдача паспорта',
                'verbose_name_plural': 'Выдача паспортов',
                'ordering': ['-pub_date', '-pk'],
            },
        ),
    ]
